[package]
name = "icefunprog"
version = "0.3.0"
edition = "2021"

[workspace]

[dependencies]
icefun = { path = "icefun" }
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
serialport = "4.3"
