[package]
name = "icefunprog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
serialport = "4.3"
termios = "0.3"
