name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: build
        run: cargo build --workspace

      - name: test
        run: cargo test --workspace

      - name: format
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --workspace --all-targets --no-deps -- -D warnings
